spring:
  profiles:
    active: dev
---
server:
  port: ${vcap.application.port:8080}
---
spring:
  profiles: dev
zuul:
  routes:
    purchase-service:
      path: /purchase-service/**
      serviceId: purchase-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
---
spring:
  profiles: docker
zuul:
  routes:
    purchase-service:
      path: /purchase-service/**
      serviceId: purchase-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/