spring:
  profiles:
    active: dev
---
server:
  port: ${vcap.application.port:8761}
---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
---
spring:
  profiles: docker
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0